[package]
name = "metadata"
version = "0.1.0"
authors = ["Zhiming Wang <i@zhimingwang.org>"]

[lib]
name = "metadata"
path = "src/lib.rs"

[dependencies]
clap = "2.32.0"
digest = { version = "0.7.5", features = ["std"] }
env_logger = "0.5.13"
# TODO: at release time, fix the commit
ffmpeg = { git = "https://github.com/zmwangx/rust-ffmpeg" }
handlebars = "1.0.3"
lazy_static = "1.1.0"
log = "0.4.5"
regex = "1.0.5"
serde = "1.0.78"
sha2 = "0.7.1"
serde_derive = "1.0.79"

[dev-dependencies]
quickcheck = "0.7.1"
tempfile = "3.0.3"
